name: culture_bridge
description: Culture Bridge responsive Flutter frontend.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.13.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^18.0.2
  shared_preferences: ^2.5.6
  flutter_svg: ^2.3.0
  freezed_annotation: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^4.0.2
  build_runner: ^2.16.2
flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: YoungSerif
      fonts:
        - asset: assets/fonts/YoungSerif-Regular.ttf
    - family: Spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf
        - asset: assets/fonts/Spectral-Italic.ttf
          style: italic
    - family: CourierPrime
      fonts:
        - asset: assets/fonts/CourierPrime-Regular.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Variable.ttf
    - family: NotoSerifTC
      fonts:
        - asset: assets/fonts/NotoSerifTC-Variable.ttf
